import type { Work, WorkBranch, WorkComment, WorkVersion } from "./types";

const users = {
  mika: { id: "user-mika", name: "Mika", handle: "@mika" },
  north: { id: "user-north", name: "North Lab", handle: "@northlab" },
  yun: { id: "user-yun", name: "Yun", handle: "@yun" },
  aria: { id: "user-aria", name: "Aria", handle: "@aria" },
};

export const works: Work[] = [
  {
    id: "chair-001",
    type: "model",
    title: "Modular Lounge Chair",
    description:
      "A clean modular chair model designed for remixing layout, cushions, and material systems.",
    owner: users.mika,
    coverTone: "#3b6f8f",
    rootVersionId: "chair-v1",
    defaultBranchId: "chair-main",
    tags: ["furniture", "interior", "editable"],
    likeCount: 248,
    favoriteCount: 76,
    branchCount: 8,
    commentCount: 19,
    createdAt: "2026-05-19",
    updatedAt: "2026-06-12",
  },
  {
    id: "plaza-tiles-001",
    type: "material",
    title: "Weathered Plaza Tiles",
    description:
      "Procedural tile material with warm worn edges, suitable for urban plazas and courtyards.",
    owner: users.north,
    coverTone: "#b75b43",
    rootVersionId: "tiles-v1",
    defaultBranchId: "tiles-main",
    tags: ["material", "urban", "procedural"],
    likeCount: 183,
    favoriteCount: 51,
    branchCount: 5,
    commentCount: 12,
    createdAt: "2026-05-28",
    updatedAt: "2026-06-10",
  },
  {
    id: "kiosk-001",
    type: "model",
    title: "Pop-up Gallery Kiosk",
    description:
      "A small exhibition kiosk model with branchable display panels and lighting variations.",
    owner: users.yun,
    coverTone: "#5d6f4f",
    rootVersionId: "kiosk-v1",
    defaultBranchId: "kiosk-main",
    tags: ["architecture", "gallery", "lighting"],
    likeCount: 316,
    favoriteCount: 104,
    branchCount: 13,
    commentCount: 27,
    createdAt: "2026-04-30",
    updatedAt: "2026-06-11",
  },
  {
    id: "fabric-001",
    type: "material",
    title: "Soft Woven Fabric",
    description:
      "A subtle woven fabric material with editable color, roughness, and bump intensity.",
    owner: users.aria,
    coverTone: "#d8dfc8",
    rootVersionId: "fabric-v1",
    defaultBranchId: "fabric-main",
    tags: ["material", "fabric", "soft"],
    likeCount: 91,
    favoriteCount: 34,
    branchCount: 3,
    commentCount: 8,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-09",
  },
];

export const branches: WorkBranch[] = [
  {
    id: "chair-main",
    workId: "chair-001",
    name: "main",
    baseVersionId: "chair-v1",
    headVersionId: "chair-v3",
    owner: users.mika,
    createdAt: "2026-05-19",
    updatedAt: "2026-06-12",
  },
  {
    id: "chair-soft-seat",
    workId: "chair-001",
    name: "aria/soft-seat",
    baseVersionId: "chair-v2",
    headVersionId: "chair-a2",
    owner: users.aria,
    createdAt: "2026-06-08",
    updatedAt: "2026-06-12",
  },
  {
    id: "tiles-main",
    workId: "plaza-tiles-001",
    name: "main",
    baseVersionId: "tiles-v1",
    headVersionId: "tiles-v2",
    owner: users.north,
    createdAt: "2026-05-28",
    updatedAt: "2026-06-10",
  },
  {
    id: "kiosk-main",
    workId: "kiosk-001",
    name: "main",
    baseVersionId: "kiosk-v1",
    headVersionId: "kiosk-v3",
    owner: users.yun,
    createdAt: "2026-04-30",
    updatedAt: "2026-06-11",
  },
  {
    id: "fabric-main",
    workId: "fabric-001",
    name: "main",
    baseVersionId: "fabric-v1",
    headVersionId: "fabric-v2",
    owner: users.aria,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-09",
  },
];

export const versions: WorkVersion[] = [
  {
    id: "chair-v1",
    workId: "chair-001",
    branchId: "chair-main",
    parentVersionId: null,
    author: users.mika,
    title: "Initial blockout",
    description: "Base proportions and modular frame.",
    assetLabel: "chair-base.glb",
    thumbnailTone: "#3b6f8f",
    changeNote: "Created the initial lounge chair model.",
    createdAt: "2026-05-19",
  },
  {
    id: "chair-v2",
    workId: "chair-001",
    branchId: "chair-main",
    parentVersionId: "chair-v1",
    author: users.mika,
    title: "Armrest refinement",
    description: "Adjusted side modules and cushion spacing.",
    assetLabel: "chair-armrest.glb",
    thumbnailTone: "#5d6f4f",
    changeNote: "Refined the silhouette and proportions.",
    createdAt: "2026-06-03",
  },
  {
    id: "chair-v3",
    workId: "chair-001",
    branchId: "chair-main",
    parentVersionId: "chair-v2",
    author: users.mika,
    title: "Main branch material pass",
    description: "Added neutral fabric and darker metal frame.",
    assetLabel: "chair-main-material.glb",
    thumbnailTone: "#d8dfc8",
    changeNote: "Added the default material treatment.",
    createdAt: "2026-06-12",
  },
  {
    id: "chair-a2",
    workId: "chair-001",
    branchId: "chair-soft-seat",
    parentVersionId: "chair-v2",
    author: users.aria,
    title: "Soft seat variation",
    description: "A softer cushion branch with warmer upholstery.",
    assetLabel: "chair-soft-seat.glb",
    thumbnailTone: "#b75b43",
    changeNote: "Branched from v2 and explored softer seating.",
    createdAt: "2026-06-12",
  },
  {
    id: "tiles-v1",
    workId: "plaza-tiles-001",
    branchId: "tiles-main",
    parentVersionId: null,
    author: users.north,
    title: "Base material",
    description: "Initial weathered tile material.",
    assetLabel: "plaza-tiles.mat",
    thumbnailTone: "#b75b43",
    changeNote: "Created base material parameters.",
    createdAt: "2026-05-28",
  },
  {
    id: "tiles-v2",
    workId: "plaza-tiles-001",
    branchId: "tiles-main",
    parentVersionId: "tiles-v1",
    author: users.north,
    title: "Edge wear update",
    description: "Improved edge wear and surface contrast.",
    assetLabel: "plaza-tiles-v2.mat",
    thumbnailTone: "#a56f45",
    changeNote: "Adjusted roughness and edge wear masks.",
    createdAt: "2026-06-10",
  },
  {
    id: "kiosk-v1",
    workId: "kiosk-001",
    branchId: "kiosk-main",
    parentVersionId: null,
    author: users.yun,
    title: "Kiosk shell",
    description: "Initial exhibition kiosk shell.",
    assetLabel: "kiosk-shell.glb",
    thumbnailTone: "#5d6f4f",
    changeNote: "Created kiosk massing.",
    createdAt: "2026-04-30",
  },
  {
    id: "kiosk-v3",
    workId: "kiosk-001",
    branchId: "kiosk-main",
    parentVersionId: "kiosk-v1",
    author: users.yun,
    title: "Lighting study",
    description: "Added display panels and lighting variations.",
    assetLabel: "kiosk-lighting.glb",
    thumbnailTone: "#3b6f8f",
    changeNote: "Added the current lighting setup.",
    createdAt: "2026-06-11",
  },
  {
    id: "fabric-v1",
    workId: "fabric-001",
    branchId: "fabric-main",
    parentVersionId: null,
    author: users.aria,
    title: "Base weave",
    description: "Initial woven fabric material.",
    assetLabel: "fabric-base.mat",
    thumbnailTone: "#d8dfc8",
    changeNote: "Created fabric base shader settings.",
    createdAt: "2026-06-01",
  },
  {
    id: "fabric-v2",
    workId: "fabric-001",
    branchId: "fabric-main",
    parentVersionId: "fabric-v1",
    author: users.aria,
    title: "Bump detail pass",
    description: "Improved weave bump and roughness.",
    assetLabel: "fabric-bump-pass.mat",
    thumbnailTone: "#c6d2b0",
    changeNote: "Increased weave definition.",
    createdAt: "2026-06-09",
  },
];

export const comments: WorkComment[] = [
  {
    id: "comment-1",
    workId: "chair-001",
    versionId: "chair-v3",
    author: users.north,
    content: "The main branch reads well. The cushion seams could become editable parameters.",
    createdAt: "2026-06-12",
  },
  {
    id: "comment-2",
    workId: "chair-001",
    versionId: "chair-a2",
    author: users.yun,
    content: "This branch feels softer. I would like to try a lower backrest variant.",
    createdAt: "2026-06-13",
  },
  {
    id: "comment-3",
    workId: "plaza-tiles-001",
    versionId: "tiles-v2",
    author: users.mika,
    content: "The edge wear is useful for exterior scenes. Nice material direction.",
    createdAt: "2026-06-11",
  },
];
